#!/usr/bin/env python3
"""
Upload the working tree to GitHub without the git CLI.

    python scripts/upload_github.py ["commit message"]

Builds one commit that mirrors the project (minus raw/backup data, which
exceeds GitHub's 100 MB file limit) and points the default branch at it,
via the REST Git Data API. Auth comes from the credential already stored
by Git Credential Manager (`git credential fill`) -- git itself is only
used as a keychain, never for push. The token is never printed.
"""

from __future__ import annotations

import base64
import fnmatch
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request

OWNER = "parkman00771188"
REPO = "earthquake-layer-3d"
API = "https://api.github.com"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Kept out of the repo: raw source data (catalog.csv alone is >100 MB, over
# GitHub's hard per-file limit), local backups, and caches. All of it is
# regenerated by update.bat.
EXCLUDE_DIRS = {".git", "__pycache__", "node_modules"}
EXCLUDE_PREFIXES = ("data/raw/", "data/backup-")
EXCLUDE_GLOBS = ("*.pyc", "*.log", ".upload_cache.json")
MAX_BYTES = 95 * 1024 * 1024

# Local (path -> size/mtime/sha) memo: blobs already pushed in an earlier
# commit live in the repository forever, so unchanged files need no re-upload.
CACHE = os.path.join(ROOT, ".upload_cache.json")


def fail(msg: str) -> None:
    print(f"[upload] ERROR: {msg}")
    sys.exit(1)


def credential() -> tuple[str, str]:
    """Ask git's credential helper for the stored github.com login."""
    env = {**os.environ, "GCM_INTERACTIVE": "never", "GIT_TERMINAL_PROMPT": "0"}
    try:
        out = subprocess.run(
            ["git", "credential", "fill"],
            input="protocol=https\nhost=github.com\n\n",
            capture_output=True, text=True, env=env, timeout=30,
        )
    except FileNotFoundError:
        fail("git is not installed; cannot read the stored credential")
    if out.returncode != 0:
        fail("no stored github.com credential found "
             "(sign in once with GitHub Desktop or git, or supply a PAT)")
    kv = dict(line.split("=", 1) for line in out.stdout.splitlines() if "=" in line)
    if "password" not in kv:
        fail("credential helper returned no token")
    return kv.get("username", "x-access-token"), kv["password"]


def request(method: str, url: str, token: str, body: dict | None = None) -> dict:
    data = json.dumps(body).encode() if body is not None else None
    # GitHub answers 502/503 now and then on large blob pushes; a couple of
    # retries is the difference between a finished upload and a lost one.
    for attempt in range(4):
        req = urllib.request.Request(url, data=data, method=method, headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": f"{REPO}-uploader",
        })
        try:
            with urllib.request.urlopen(req, timeout=600) as r:
                return json.load(r)
        except urllib.error.HTTPError as e:
            if e.code < 500 or attempt == 3:
                raise
            print(f"[upload] {e.code} from GitHub, retrying in {5 * (attempt + 1)}s")
            time.sleep(5 * (attempt + 1))
        except (TimeoutError, urllib.error.URLError) as e:
            if attempt == 3:
                raise
            print(f"[upload] {type(e).__name__}, retrying in {5 * (attempt + 1)}s")
            time.sleep(5 * (attempt + 1))
    raise RuntimeError("unreachable")


def collect() -> list[str]:
    files = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for name in filenames:
            rel = os.path.relpath(os.path.join(dirpath, name), ROOT).replace("\\", "/")
            if rel.startswith(EXCLUDE_PREFIXES):
                continue
            if any(fnmatch.fnmatch(name, g) for g in EXCLUDE_GLOBS):
                continue
            files.append(rel)
    return sorted(files)


def main() -> int:
    message = sys.argv[1] if len(sys.argv) > 1 else "Update from local working tree"
    user, token = credential()

    who = request("GET", f"{API}/user", token).get("login", "?")
    repo = request("GET", f"{API}/repos/{OWNER}/{REPO}", token)
    if not repo.get("permissions", {}).get("push"):
        fail(f"account '{who}' has no push access to {OWNER}/{REPO}")
    branch = repo["default_branch"]
    print(f"[upload] as {who} -> {OWNER}/{REPO} ({branch})")

    files = collect()
    total = sum(os.path.getsize(os.path.join(ROOT, f)) for f in files)
    print(f"[upload] {len(files)} files, {total / 1e6:.1f} MB")

    parents = []
    try:
        ref = request("GET", f"{API}/repos/{OWNER}/{REPO}/git/ref/heads/{branch}", token)
        parents = [ref["object"]["sha"]]
    except urllib.error.HTTPError as e:
        if e.code not in (404, 409):       # 409: "Git Repository is empty"
            raise
        # A repo with no commits rejects the Git Data API outright, so seed it
        # through the contents API first.
        print("[upload] empty repository -- creating bootstrap commit")
        seed = request("PUT", f"{API}/repos/{OWNER}/{REPO}/contents/.gitignore", token, {
            "message": "Initial commit",
            "content": base64.b64encode(
                open(os.path.join(ROOT, ".gitignore"), "rb").read()).decode(),
            "branch": branch,
        })
        parents = [seed["commit"]["sha"]]

    cache = {}
    if os.path.exists(CACHE):
        try:
            with open(CACHE, encoding="utf-8") as fh:
                cache = json.load(fh)
        except Exception:
            cache = {}

    tree = []
    reused = 0
    for rel in files:
        path = os.path.join(ROOT, rel)
        st = os.stat(path)
        if st.st_size > MAX_BYTES:
            print(f"[upload] ! skipping {rel} ({st.st_size / 1e6:.0f} MB > GitHub limit)")
            continue
        hit = cache.get(rel)
        if hit and hit["size"] == st.st_size and hit["mtime"] == int(st.st_mtime):
            sha = hit["sha"]
            reused += 1
        else:
            with open(path, "rb") as fh:
                content = base64.b64encode(fh.read()).decode()
            blob = request("POST", f"{API}/repos/{OWNER}/{REPO}/git/blobs", token,
                           {"content": content, "encoding": "base64"})
            sha = blob["sha"]
            cache[rel] = {"size": st.st_size, "mtime": int(st.st_mtime), "sha": sha}
            print(f"[upload]   {rel} ({st.st_size / 1e3:.0f} KB)")
        tree.append({"path": rel, "mode": "100644", "type": "blob", "sha": sha})
    if reused:
        print(f"[upload] {reused} unchanged file(s) reused without re-upload")

    # No base_tree: the commit mirrors the local set exactly, so files removed
    # locally disappear from the repo too instead of lingering forever.
    new_tree = request("POST", f"{API}/repos/{OWNER}/{REPO}/git/trees", token,
                       {"tree": tree})
    commit = request("POST", f"{API}/repos/{OWNER}/{REPO}/git/commits", token,
                     {"message": message, "tree": new_tree["sha"], "parents": parents})

    # A ref update can 422 ("Object does not exist") for a few seconds while
    # the just-created commit replicates on GitHub's side; retry briefly.
    for attempt in range(3):
        try:
            if parents:
                request("PATCH", f"{API}/repos/{OWNER}/{REPO}/git/refs/heads/{branch}",
                        token, {"sha": commit["sha"], "force": False})
            else:
                request("POST", f"{API}/repos/{OWNER}/{REPO}/git/refs", token,
                        {"ref": f"refs/heads/{branch}", "sha": commit["sha"]})
            break
        except urllib.error.HTTPError as e:
            if e.code != 422 or attempt == 2:
                raise
            time.sleep(3)

    with open(CACHE, "w", encoding="utf-8") as fh:
        json.dump(cache, fh)
    print(f"[upload] done: https://github.com/{OWNER}/{REPO}/commit/{commit['sha'][:12]}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:300]
        fail(f"GitHub API {e.code} on {e.url}: {detail}")
